# https://github.com/mojombo/jekyll/wiki/Configuration for more settings
title: JANDI tech blog
description: 안녕하세요. 잔디 서비스를 개발중인 토스랩 식구들의 블로그입니다.

# https://help.github.com/articles/using-jekyll-with-pages/#configuring-jekyll
safe: true
lsi: false

highlighter: pygments
permalink: pretty
markdown: redcarpet

redcarpet:
    extensions:
        - no_intra_emphasis
        - fenced_code_blocks
        - tables
        - strikethrough
        - superscript
        - autolink
        - hard_wrap

gems:
    - jemoji

paginate: 5

author_dir: author

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html


#paginate_path: "page:num"
#exclude: ["README.md"] # files to exclude
#markdown: kramdown

#BASE_PATH:
