# https://github.com/mojombo/jekyll/wiki/Configuration for more settings
title: JANDI tech blog
description: 안녕하세요. 잔디 서비스를 개발중인 토스랩 식구들의 블로그입니다.

# https://help.github.com/articles/using-jekyll-with-pages/#configuring-jekyll
safe: true
lsi: false

highlighter: pygments
permalink: pretty
markdown: redcarpet

redcarpet:
    extensions:
        - no_intra_emphasis
        - fenced_code_blocks
        - tables
        - strikethrough
        - superscript
        - autolink
        - hard_wrap

gems:
    - jemoji

paginate: 10

authors:
    tosslab:
        name: "TossLab, Inc."
        nickname: "TossLab Dev Team"
        email: "toss@tosslab.com"
        github: "tosslab"
        bio: "TossLab Tech Blog"
    justin:
        name: "최영근"
        nickname: "Justin"
        email: "justin@tosslab.com"
        bio: "내가 바로 저스틴"
    mk:
        name: "최민기"
        nickname: "MK"
        gravatar: "117003ad8b8e2f8601a33e05197a26ab"
        email: "mk@tosslab.com"
        bio: "기대가 큽니다"
        blog: "https://www.jandi.com"
        twitter: "akamk87"
        facebook: "agileup"
        github: "agileup"
    steve:
        name: "정승욱"
        nickname: "Steve"

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html


#paginate_path: "page:num"
#exclude: ["README.md"] # files to exclude
#markdown: kramdown

#BASE_PATH:
