# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 3 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: true
markdown: kramdown


defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: tosslab

description: Stylish Jekyll Theme
author:
  name: Toss Lab, Inc.
  email: toss@tosslab.com
  github: tosslab
#  twitter: dbtek
#  pinterest: asd123
#  linkedin: asd123
  bio: TossLab Tech Blog
  email_md5: 726351295ec82e145928582f595aa3aa

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

BASE_PATH:
